services:
  duckierace_env:
    build: .
    container_name: duckie_ros
    network_mode: "host"
    environment:
      # These variables will be populated by the .env file
      - ROS_MASTER_URI=http://${DUCKIEBOT_IP}:11311
      - ROS_IP=${HOST_IP}
      - VEHICLE_NAME=${VEHICLE_NAME}
    volumes:
      - .:/workspace 
    command: sleep infinity
