duck:
  hh: 21
  hl: 0
  sh: 255
  sl: 220
  vh: 255
  vl: 200
lane_image:
  bottom_left_x: 606
  bottom_left_y: 382
  bottom_right_x: -29
  bottom_right_y: 382
  top_left_x: 159
  top_left_y: 218
  top_right_x: 441
  top_right_y: 218
pid_regler:
  d: 30
  i: 50
  max_vel: 100
  p: 50
red:
  hh: 11
  hl: 0
  sh: 255
  sl: 60
  vh: 255
  vl: 120
turn_control:
  front_tunr_y: 50
  front_turn_x: 0
  left_turn_x: -50
  left_turn_y: 40
  right_turn_x: 20
  right_turn_y: 20
turn_detect:
  front_x: 218
  front_y: 171
  left_x: 29
  left_y: 241
  right_x: 441
  right_y: 194
white:
  hh: 255
  hl: 0
  sh: 41
  sl: 0
  vh: 255
  vl: 161
yellow:
  hh: 60
  hl: 15
  sh: 255
  sl: 60
  vh: 255
  vl: 120